= Notes Storage Facility (NSF) database file format
Analysis of the NFS database file format

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary
The Notes Storage Facility (NSF) database file is used by (IBM) Lotus Notes and 
Domino to store different kind of objects like e-mail, appointments and 
documents, but also application forms and views.

This document is intended as a working document for the NSF specification. 
Which should allow existing Open Source forensic tooling to be able to process 
this partitioning schema.

[preface]
== Document information
[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the Notes Storage Facility (NSF) database format.
| Classification: | Public
| Keywords: | Lotus Notes, Lotus Domino, Notes Storage Facility, NSF
|===

[preface]
== License
....
Copyright (C) 2010-2016, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the 
terms of the GNU Free Documentation License, Version 1.3 or any later version 
published by the Free Software Foundation; with no Invariant Sections, no 
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included 
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history
[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | February 2010 | Initial version.
| 0.0.2 | J.B. Metz | November 2012 | Additional information and email update.
| 0.0.2 | J.B. Metz | February 2016 | Switched to asciidoc format.
|===

:numbered:
== Overview
The Notes Storage Facility (NSF) database file is used by (IBM) Lotus Notes and 
Domino to store different kind of objects like e-mail, appointments and 
documents, but also application forms and views.

[yellow-background]*An NSF is also referred to as an object store?*

An Notes Storage Facility (NSF) database file consist of the following 
distinguishable elements:

* file header
* database header
* various
** superblock
** bucket descriptor block
** bitmap
** Record Relocation Vector bucket
** summary buckets
** non-summary buckets

An NSF database can contain various types data stored in notes:
* access control list note
* icon note
** design note
** resource
* help-using document
** design note
** resource
* help-about document
** design note
** resource
* view note(s)
** design note
* form note
** design note
* agent note(s)
** design note
* data note(s)
** document
* collection(s)
** index(es)

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values | 
| Character strings | Lotus Multi-Byte Character Set (LMBCS)
|===

[yellow-background]*File size in increments of 65536?*

== Terminology
[yellow-background]*TODO: describe:*
....
extension
private
....

=== Summary and non-summary
In the Notes/Domino terminology summary refers to 'summary information' about 
items (objects) in the NSF file, e.g. document summary information like author, 
creation date and time, etc. Non-summary refers to all other type of 
information e.g. formatted text, pictures, etc.

=== Data and non-data
[yellow-background]*TODO: data refers to content items, non-data to metadata items.*

== NSF data types
=== [[nsf_date_and_time]]NSF date and time
The Domino and Notes TIMEDATE structure consists of 32-bit values that encode 
the time, the date, the time zone, and the Daylight Savings Time settings that 
were in effect when the structure was initialized.

The first 32-bit value contains the number of hundredths of seconds since 
midnight, Greenwich mean time. If only the date is important, not the time, 
this field may be set to ALLDAY (0xffffffff or -1).

The date and the time zone and Daylight Savings Time settings are encoded in 
the second 32-bit value. The 24 low-order bits contain the Julian Day, the 
number of days since January 1, 4713 BC. 

The Julian Day was originally devised as an aid to astronomers and is not the 
same as the Julian calendar. Since only days are counted, weeks, months, and 
years are ignored in calculations. The Julian Day is defined to begin at noon; 
for simplicity, Domino and Notes assume that the day begins at midnight.

The high-order byte, bits 31-24, encodes the time zone and Daylight Savings 
Time information.

* bit 31 (0x80000000) is set if Daylight Savings Time is observed;
* bit 30 (0x40000000) is set if the time zone is east of Greenwich mean time;
* bits 27-24 contain the number of hours difference between the time zone and Greenwich mean time;
* bits 29-28 contain the number of 15-minute intervals in the difference.

For example, 2:49:04 P. M., Eastern Standard Time, December 10, 1996 would be 
stored as:
....
0x006CDCC0	19 hours, 49 minutes, 4 seconds GMT
0x852563FC	DST observed, zone +5, Julian Day 2,450,428
....

If the time zone were set for Bombay, India, where Daylight Savings Time is not 
observed, 2:49:04 P. M., December 10, 1996 would be stored as:
....
0x0032B864	9 hours, 19 minutes, 4 seconds GMT
0x652563FC	No DST, zone 5 1/2 hours east of GMT, Julian Day 2,450,428
....

=== [[nsf_file_position]]NSF file position
The NSF file position is a 32-bit value that contains a file offset value 
divided by 256 (0x100).

=== On-disk structure signatures
The NSF format uses on-disk structure (ODS) signatures to mark the start and 
size of data structures.

==== Byte signature
The byte signatures (BSIG) is 2 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | | Signature
| 1 | 1 | | Structure size
|===

==== Word signature
The word signatures (WSIG) is 4 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | | Signature
| 1 | 1 | 0xff | Marker value
| 2 | 2 | | Structure size
|===

==== Long signature
The long signatures (LSIG) is 4 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | | Signature
| 1 | 1 | 0x00 | Marker value
| 2 | 4 | | Structure size
|===

== The file header
The file header is 6 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | 0x1a 0x00 | Signature
| 2 | 4 | | The database header size
|===

Notes/Domino considers the file header a long-signature (LSIG) of the database 
header.

== The database header
The database header contains the following values:

* database information
** database identifier (DBID)
** flags
* replication information
* database information buffer
** title
** categories
** class
** design class (template name)
* special note identifiers
* padding
* database information 2
* database information 3
* database information 4
* database information 5
* padding

* database instance identifier (DBIID)
* replication history

* [yellow-background]*TODO: user activity log*
* [yellow-background]*TODO: UNID index*

=== Database information
The database information (DBINFO) is 178 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Format version +
on-disk structure (ODS) version +
See section: <<format_version,Format version>>
| 4 | 8 | | Database identifier (DBID) +
Value consists an NSF date and time but is considered as an identifier +
See section: <<nsf_date_and_time,NSF date and time>> +
[yellow-background]*Also used as creation date and time?*
| 12 | 2 | | Application version
| 14 | 4 | | Non-data Record Relocation Vector (RRV) bucket position +
See section: <<nsf_file_position,NSF file position>>
| 18 | 4 | | (Next) available non-data Record Relocation Vector (RRV) identifier
| 22 | 2 | | Number of available non-data Record Relocation Vectors (RRVs)
| 24 | 4 | | Activity log offset
| 28 | 8 | | Bucket (last) modification date and time +
Value consists of an NSF date and time +
See section: <<nsf_date_and_time,NSF date and time>> +
[yellow-background]*Also used as modification date and time?*
| 36 | 2 | | Database class +
[yellow-background]*TODO: add description*
| 38 | 2 | | Database flags +
See section: <<database_flags,Database flags>>
| 40 | 4 | | Bucket Descriptor Block (BDB) size
| 44 | 4 | | Bucket Descriptor Block (BDB) position +
See section: <<nsf_file_position,NSF file position>>
| 48 | 2 | | Bucket Descriptor Table (BDT) size
| 50 | 4 | | Bucket Descriptor Table (BDT) [yellow-background]*position?*
| 54 | 2 | | Bucket Descriptor Table (BDT) [yellow-background]*bitmaps?*
| 56 | 4 | | Data Record Relocation Vector (RRV) bucket position +
See section: <<nsf_file_position,NSF file position>>
| 60 | 4 | | First data Record Relocation Vector (RRV) identifier +
[yellow-background]*Probably the first defined RRV not the first used*
| 64 | 4 | | (Next) available data Record Relocation Vector (RRV) identifier
| 68 | 2 | | Number of available data Record Relocation Vectors (RRVs)
| 70 | 2 | | Record Relocation Vector (RRV) bucket size
| 72 | 2 | | Summary bucket size
| 74 | 2 | | Bitmap size
| 76 | 2 | | Allocation granularity
| 78 | 4 | | Extension granularity
| 82 | 4 | | File size +
The value contains 256 byte increments +
[yellow-background]*If version >= 0x15?*
| 86 | 4 | | Number of file truncations
| 90 | 4 | | Delivery sequence number
| 94 | 4 | | Number of Bucket Descriptor Block (BDB) replacements
| 98 | 4 | | Number of allocated Record Relocation Vectors (RRVs)
| 102 | 4 | | Number of de-allocations
| 106 | 4 | | Number of non-bucket allocations
| 110 | 4 | | Number of bucket allocations
| 114 | 8 | | Folder (last) modification date and time +
Value consists of an NSF date and time +
See section: <<nsf_date_and_time,NSF date and time>>
| 122 | 4 | | Data note identifier table [yellow-background]*position?*
| 126 | 4 | | Data note identifier table size
| 134 | 8 | | Data (last) modification date and time +
Value consists of an NSF date and time +
See section: <<nsf_date_and_time,NSF date and time>>
| 142 | 8 | | Next purge date and time +
Value consists of an NSF date and time +
See section: <<nsf_date_and_time,NSF date and time>>
| 150 | 4 | | Version 3 named object hash [yellow-background]*position?*
| 154 | 4 | | Named object hash [yellow-background]*position?*
| 158 | 8 | | [yellow-background]*Private* (last) modification date and time +
Value consists of an NSF date and time +
See section: <<nsf_date_and_time,NSF date and time>>
| 166 | 2 | | Maximum number of [yellow-background]*privates?*
| 168 | 2 | | named object hash version +
[yellow-background]*Format version < 0x1c*
| 170 | 8 | | Non-data (last) modification date and time +
Value consists of a NSF date and time but is considered as an identifier +
See section: <<nsf_date_and_time,NSF date and time>>
|===

==== [[format_version]]Format version

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 16 | | Notes 1.x, 2x
| 17 | | Notes 3.x
| 20 | | Notes 4.x
| 41 | | Notes 5.x
| 43 | | Notes 6, 7 and 8
| 48 | | Notes 8
| 51 | | Notes 8.5
|===

==== [[database_flags]]Database flags
[yellow-background]*TODO: add text*

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| | DBFLAG_FIXUP | 
| | DBFLAG_CORRUPT | 
| | DBFLAG_SPARSE_RRVS | 
| | DBFLAG_PURGE_ON | 
| | DBFLAG_REPLFORMULA | 
| | DBFLAG_FULL_FOLDER_REPL | 
| | DBFLAG_FOLDERS_CONVERTED | 
| | DBFLAG_MAX_SPECIFIED | 
| | DBFLAG_FIXUP_FOLDERS | 
| | DBFLAG_DELSEQ_CORRECTED | 
| | DBFLAG_DEFERRED_UNIDINDEX | 
| | DBFLAG_FIXUP_CLEAR_LSN | 
| | DBFLAG_IS_A_BACKUP | 
| | DBFLAG_UNLOGGED_CHANGE_INPROGR | 
| | DBFLAG_DESIGN_IN_NAMOBJ |
|===

=== Database replication information
The database replication information (DBREPLICAINFO) is 20 bytes of size and 
consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | Replication identifier +
Value consists of a NSF date and time (in local time) but is considered as an identifier +
See section: <<nsf_date_and_time,NSF date and time>>
| 8 | 2 | | Replication flags +
See section: <<replication_flags,Replication flags>>
| 10 | 2 | | Replication cutoff interval +
Value in days
| 12 | 8 | | Replication cutoff date and time +
Value consists of a NSF date and time +
See section: <<nsf_date_and_time,NSF date and time>>
|===

==== [[replication_flags]]Replication flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0001 | | [yellow-background]*spare was COPY_ACL*
| 0x0002 | | [yellow-background]*spare*
| 0x0004 | REPLFLG_DISABLE | Disable replication
| 0x0008 | REPLFLG_UNREADIFFNEW | Mark unread only if newer note
| 0x0010 | REPLFLG_IGNORE_DELETES | Don't propagate deleted notes when  replicating from this database
| 0x0020 | REPLFLG_HIDDEN_DESIGN | UI does not allow perusal of Design
| 0x0040 | REPLFLG_DO_NOT_CATALOG | Do not list in catalog
| 0x0080 | REPLFLG_CUTOFF_DELETE | Auto-Delete documents prior to cutoff date
| 0x0100 | REPLFLG_NEVER_REPLICATE | DB is not to be replicated at all 
| 0x0200 | REPLFLG_ABSTRACT | Abstract during replication
| 0x0400 | REPLFLG_DO_NOT_BROWSE | Do not list in database add
| 0x0800 | REPLFLG_NO_CHRONOS | Do not run chronos on database
| 0x1000 | REPLFLG_IGNORE_DEST_DELETES | Don't replicate deleted notes into destination database
| 0x2000 | REPLFLG_MULTIDB_INDEX | Include in Multi Database indexing
|===

The 2 MSB are used to store the replication priority

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0xc000 | REPLFLG_PRIORITY_LOW | Low priority
| 0x0000 | REPLFLG_PRIORITY_MED | Medium priority
| 0x4000 | REPLFLG_PRIORITY_HI | High priority
|===

=== Database information buffer
The database information buffer is 128 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | Database title
| ... | 1 | 0x0a | Categories separator ("\n")
| | | | Categories
| ... | 1 | 0x23 | Class separator ("#")
| | | | Class
| ... | 1 | 0x32 | Design class separator ("2")
| ... | ... | | Database design class (template name)
| ... | ... | 0x00 | End of database information buffer ("\0")
| ... | ... | | [yellow-background]*Unknown (Remnant data)*
|===

=== Special note identifier array
The special note identifier array is 128 byte of size and contains 48 32-bit 
note identifier values.

....
NOTE HIERARCHY DISABLED 
INDICES ARE COMPRESSED 
BUCKETS ARE COMPRESSED 
COMPRESSION PREVIOUSLY ENABLED 
UNREAD MARKS NOT MAINTAINED 
LAST ACCESSED TIMES MAINTAINED
....

=== Padding

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 64 | | [yellow-background]*Unknown (padding)*
|====

=== Database information 2
The database information (DBINFO2) is [yellow-background]*124?* bytes of size 
and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | Last fix-up date and time +
Value consists of an NSF date and time +
See section: <<nsf_date_and_time,NSF date and time>>
| 8 | 4 | | Database quota limit
| 12 | 4 | | Database quota warn threshold
| 16 | 8 | | [yellow-background]*Unknown (FoldersCleanAsOf)* +
Value consists of an NSF date and time +
See section: <<nsf_date_and_time,NSF date and time>>
| 24 | 8 | | [yellow-background]*Unknown (LastPurgedNoteTime)* +
Value consists of an NSF date and time +
See section: <<nsf_date_and_time,NSF date and time>>
| 32 | 8 | | Object store replica identifier +
Value consists an NSF date and time but is considered as an identifier +
See section: <<nsf_date_and_time,NSF date and time>>
| 40 | 4 | | Superblock 1 position +
See section: <<nsf_file_position,NSF file position>>
| 44 | 4 | | Superblock 1 size
| 48 | 4 | | Superblock 2 position +
See section: <<nsf_file_position,NSF file position>>
| 52 | 4 | | Superblock 2 size
| 56 | 4 | | Superblock 3 position +
See section: <<nsf_file_position,NSF file position>>
| 60 | 4 | | Superblock 3 size
| 64 | 4 | | Superblock 4 position +
See section: <<nsf_file_position,NSF file position>>
| 68 | 4 | | Superblock 5 size
| 72 | 4 | | Maximum extension granularity
| 76 | 2 | | Summary bucket granularity
| 78 | 2 | | Non-summary bucket granularity
| 80 | 4 | | Minimum summary bucket size
| 84 | 4 | | Minimum non-summary bucket size
| 88 | 4 | | Maximum summary bucket size
| 92 | 4 | | Maximum non-summary bucket size
| 96 | 2 | | Non-summary append size
| 98 | 2 | | Non-summary append factor
| 100 | 2 | | Summary bucket fill factor
| 102 | 2 | | Non-summary bucket fill factor
| 104 | 4 | | Bucket Descriptor Block (BDB) 1 size
| 108 | 4 | | Bucket Descriptor Block (BDB) 1 position +
See section: <<nsf_file_position,NSF file position>>
| 112 | 4 | | Bucket Descriptor Block (BDB) 2 size
| 116 | 4 | | Bucket Descriptor Block (BDB) 2 position +
See section: <<nsf_file_position,NSF file position>>
| 120 | 4 | | [yellow-background]*Unknown*
|===

=== Database information 3
The database information (DBINFO3) is [yellow-background]*44?* bytes of size 
and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | [yellow-background]*Unknown (ExpirationDays)*
| 2 | 1 | | [yellow-background]*Unknown (LSECSetupState)*
| 3 | 3 | | [yellow-background]*Unknown (LSECFlags)*
| 6 | 12 | | [yellow-background]*Unknown (LSECEncKeyDataLen)*
| 18 | 8 | | [yellow-background]*Unknown (LSECKeyCreationTime)*
| 26 | 4 | | [yellow-background]*Unknown (LSECEncKeyDataPos)*
| 30 | 4 | | [yellow-background]*Unknown (LSECExtKeyDataPos)*
| 34 | 4 | | [yellow-background]*Unknown (LSECExtKeyDataLen)*
| 38 | 6 | | [yellow-background]*Unknown (VirtualOffset)*
|===

==== States

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| | LSEC_STATE_NONE | 
| | LSEC_STATE_DONE | 
| | LSEC_STATE_NEXTENCRYPT | 
| | LSEC_STATE_NEXTDECRYPT |
|===

==== Flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| | LSEC_PUBLICKEY | 
| | LSEC_SECRETKEY | 
| | LSEC_INTERNATIONAL | 
| | LSEC_USEBKOBJECT | 
|===

=== Database information 4
The database information (DBINFO4) is  [yellow-background]*X?* bytes of size 
and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 14 | | [yellow-background]*Unknown*
| 662 | 4 | | [yellow-background]*Unknown (NextVirtualRRV)*
| 666 | 2 | | [yellow-background]*Unknown (BackupTag)*
| 668 | 4 | | [yellow-background]*Unknown (HighestFolderValidityID)*
| 672 | 16 | | [yellow-background]*Unknown (DbOptions)*
| 688 | 8 | | [yellow-background]*Unknown (DBIID (unique random number))*
| 696 | 8 | | [yellow-background]*Unknown (DBIID Creation)*
| 704 | 8 | | [yellow-background]*Unknown (Last successful backup)*
| 712 | 8 | | [yellow-background]*Unknown (LastSBWriteCount)*
| 720 | 8 | | [yellow-background]*Unknown (LastBackupTimeLSN)*
| 728 | 4 | | [yellow-background]*Unknown (LogNum)*
| 732 | 36 | | [yellow-background]*Unknown*
|===

=== Database information 5
The database information (DBINFO5) is [yellow-background]*168?* bytes of size 
and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 x 8 | | [yellow-background]*Unknown (LogID)*
| 16 | 8 | | [yellow-background]*Unknown (LastFullCompactionTime)*
| 24 | 4 | | [yellow-background]*Unknown (SizeSCOSLow)*
| 28 | 4 | | [yellow-background]*Unknown (SizeSCOSHigh)*
| 32 | 2 | | [yellow-background]*Unknown (DollarRevisionsLimit)*
| 34 | 2 | | [yellow-background]*Unknown (DollarUpdatedByLimit)*
| 36 | 4 | | [yellow-background]*Unknown (InboxRRV)*
| 40 | 2 | | [yellow-background]*Unknown (SoftDeleteRetainDuration)*
| 42 | 2 | | [yellow-background]*Unknown (BackupFlags)*
| 44 | 8 | | [yellow-background]*Unknown (Start time of last backup)*
| 52 | 2 | | [yellow-background]*Unknown (Flags5)*
| 54 | 4 | | [yellow-background]*Unknown (UsedSpace)*
| 58 | 8 | | [yellow-background]*Unknown (UsedSpaceRecalcTime)*
| 66 | 8 | | [yellow-background]*Unknown (DesignModified)*
| 74 | 8 | | [yellow-background]*Unknown (LastCloseLSN)*
| 82 | 4 | | [yellow-background]*Unknown (MarkCorruptLine)*
| 86 | 12 | | [yellow-background]*Unknown (MarkCorruptFile)*
| 98 | 8 | | [yellow-background]*Unknown (UnreadLogModified)*
| 106 | 8 | | [yellow-background]*Unknown (RefreshDesignModTime)*
| 114 | 8 | | [yellow-background]*Unknown (ProfileModified)*
| 122 | 8 | | [yellow-background]*Unknown (LastCompactionTime)*
| 130 | 4 | | [yellow-background]*Unknown (DAOSObjectRefCt)*
| 134 | 4 | | [yellow-background]*Unknown (DAOSSizeLow)*
| 138 | 4 | | [yellow-background]*Unknown (DAOSSizeHigh)*
| 142 | 8 | | [yellow-background]*Unknown (SBLastCloseLSN)*
| 150 | 8 | | [yellow-background]*Unknown (BDBLastCloseLSN)*
| 158 | 8 | | [yellow-background]*Unknown (DAOSSyncPoint)*
| 164 | 4 | | [yellow-background]*Unknown*
|===

==== Notes

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 784 | 8 | | [yellow-background]*Unknown* +
Value consists of an NSF date and time +
See section: <<nsf_date_and_time,NSF date and time>>
| 792 | 34 | | [yellow-background]*Unknown*
| 826 | 8 | | [yellow-background]*Unknown* +
Value consists of an NSF date and time +
See section: <<nsf_date_and_time,NSF date and time>>
| 834 | 8 | | [yellow-background]*Unknown* +
Value consists of an NSF date and time +
See section: <<nsf_date_and_time,NSF date and time>>
| 842 | 24 | | [yellow-background]*Unknown*
| 866 | 8 | | [yellow-background]*Unknown* +
Value consists of an NSF date and time +
See section: <<nsf_date_and_time,NSF date and time>>
| 874 | 150 | | [yellow-background]*Unknown*
|===

==== Backup flags
[yellow-background]*TODO: add text*

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| | DBBCKFLAG_IS_A_BACKUP | 
| | DBBCKFLAG_CLEAR_FIXUP | 
|===

==== Flags 5
[yellow-background]*TODO: add text*

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| | DBFLAG5_DESTROY_UNLOGGED_CONTV | 
| | DBFLAG5_NAMED_OBJECT_NEW_HASH | 
| | DBFLAG5_MODNOTELOG_HAS_DESIGN | 
| | DBFLAG5_CONVERTED_REFNOTE | 
| | DBFLAG5_HAS_PROT_ATTACHMENTS | 
| | DBFLAG5_DESTROY_UNLOGGED_CONT | 
| | DBFLAG5_FULL_UNREAD_REPL_NEEDED | 
| | DBFLAG5_FULL_DESIGN_REPL_NEEDED | 
| | DBFLAG5_DB2NSF | 
| | DBFLAG5_AUTOFIXUP_DISABLED | 
|===

=== Padding

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 90 | | [yellow-background]*Unknown (Filler2)*
|===

== Superblock
The database information 2 contains the location and size of 4 superblocks.

Most of the time an NSF file contains two superblocks. The offset of these 
superblocks is stored in the database header. Most often the first superblock 
is stored at offset 0x0400 and the second superblock at offset 0x8400. Both 
superblock are stored in 'container' which is a 0x8000 bytes of size.

The superblock consists of:

* Superblock header
* Superblock data
* Superblock footer

=== Superblock header
[yellow-background]*TODO: migrate remaining documentation.*

== Bucket Descriptor Block
[yellow-background]*TODO: migrate remaining documentation.*

== [[record_relocation_vector_bucket]]Record Relocation Vector bucket
The Record Relocation Vector (RRV) bucket consists:

* RRV (container) bucket header
* an array of RRV entries

The RRV bucket is 4096 bytes of size.

=== RRV (container) bucket header
The RRV bucket header is 32 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
4+|_Byte signature (BSIG)_
| 0 | 1 | 0x06 | Signature
| 1 | 1 | 0x20 | Header size +
Includes the size of the signature and size value
4+| _RRV bucket header data_
| 2 | 4 | | [yellow-background]*Unknown*
| 6 | 4 | | Initial RRV identifier
| 10 | 6 | | [yellow-background]*Unknown*
| 16 | 2 | | [yellow-background]*Unknown (block size)*
| 18 | 4 | | Checksum +
32-bit XOR of the RRV entry data
| 22 | 10 | | [yellow-background]*Unknown*
|===

=== RRV entry
There are two types of RRV entries:

* a basic RRV entry
* a BSID RRV entry

After format version 21 (0x15) the RRV was extended, instead of a file position 
the RRV also can consists of a bucket slot identifier (BSID).

[yellow-background]*Unused entries contain 0xffffffff (-1) for both A and B and/or 0?*

==== Basic RRV entry
The basic RRV entry is 4 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0.0  | 32 bits | | File position +
See section: <<nsf_file_position,NSF file position>>
|===

After format version 21 (0x15) the basic RRV entry is stored in 8 bytes.

[yellow-background]*Points to ODS type 0x07?*

==== BSID RRV entry – format version 22 and later
The BSID RRV entry is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| 0.0  | 24 bits | | Bucket identifier +
Where 1 represents the first bucket
| 3.0  | 4 bits | | [yellow-background]*Unknown*
| 3.4 | 3 bits | | Upper 3 bits of NONSUM
| 3.7 | 1 bit | | [yellow-background]*Unknown (Extended RRV flag)*
| 4.0  | 11 bits | | Slot identifier +
Where 1 represents the first slot
| 5.3 | 21 bits | | Lower 21 bits of NONSUM
|===

The BSID RRV entry requires the Extended RRV flag to be set.

== [[allocation_bitmap]]Allocation bitmap
The bitmap is 2048 bytes of size. Each bit signifies a block of 256 bytes.

== Universal identifier index
Universal identifier (UNID)

[yellow-background]*TODO: add text*

== The bucket
Data is stored in buckets ranges from 4 to 32 KiB in size. The bucket is used 
for both summary and non-summary data.

A bucket consist of:

* bucket header
* bucket entries
* bucket index
* [yellow-background]*bucket trailing data*

=== The bucket header
The bucket header is 66 bytes of size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
4+|_Byte signature (BSIG)_
| 0 | 1 | 0x02 | Signature
| 1 | 1 | 0x42 | Record size +
Includes the size of the signature and size value
4+| _Bucket header data_
| 2 | 4 | | [yellow-background]*Unknown (Bucket identifier?)*
| 6 | 4 | | Bucket size
| 10 | 8 | | Modification date and time +
Value consists of a NSF date and time +
See section: <<nsf_date_and_time,NSF date and time>>
| 18 | 20 | | [yellow-background]*Unknown (Empty values)*
| 38 | 2 | | [yellow-background]*Unknown*
| 40 | 4 | | Checksum
| 44 | 4 | | Number of slots
| 48 | 2 | | [yellow-background]*Unknown (Empty values)*
| 50 | 4 | | [yellow-background]*Unknown (Bucket footer size)*
| 54 | 4 | | [yellow-background]*Unknown*
| 58 | 4 | | [yellow-background]*Unknown*
| 62 | 4 | | [yellow-background]*Unknown*
|===

=== Bucket index
Index entries stored from back to front.

==== Bucket index entry
The bucket index entry is 4 bytes of size and consist of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Start offset of the slot entry +
The value is relative to the start of the bucket
| 2 | 2 | | Size of the slot entry
|===

== The note
The note contains:

* The note (body) header
** non-summary
** attachments
* (note) item descriptors
* (note) item values
** Summary-item values 
** Response entries or overhead 
** Non-summary-item values

=== The note header
[yellow-background]*TODO: migrate remaining documentation.*

== Compression
[yellow-background]*TODO: add text*

=== [[compression_type]]Compression type

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | COMPRESS_NONE | No compression
| 1 | COMPRESS_HUFF | CX compression (Huffman encoding)
| 2 | COMPRESS_LZ1 | LZ1 compression
|===

=== CX compression
[yellow-background]*TODO: add text*

[yellow-background]*First byte contains initial tag bit position?*

....
If first tag bit = 0 followed by uncompressed byte
if first tag bit = 1 followed by a compression tuple

If compression tuple tag bit = 0 followed by compression size - 2
If compression tuple tag bit = 1 followed by compression offset

If the compression size tag bit = 0 followed by extended compression offset
If the compression size tag bit = 1 followed by compression offset

The extended compression offset contains the upper bits (> 8) of the compression offset. The compression offset point backwards relative from the end of the uncompressed data.

In the compression tuple the number of 0 bits after a tag bit represent the size in bits of either compression size or (extended) offset.
....

=== LZ1 compression
[yellow-background]*TODO: add text*

Introduced in Notes 6

== The access control list
[yellow-background]*TODO: add text*

== Notes
=== Replication history

[cols="1,1,1,5",options="header"]
|===
| 0 | 8 | | [yellow-background]*Replication date and time*
| 8 | 2 | | [yellow-background]*Access level*
| 10 | 2 | | [yellow-background]*Access flags*
| 12 | 2 | | [yellow-background]*Replication direction*
| 14 | 4 | 30 | [yellow-background]*Server name offset (in packed data?)*
| 18 | 2 | | [yellow-background]*Server name size (in packed data?)*
| 20 | 2 | | [yellow-background]*Filename size (in packed data?)*
| 22 | 2 | | [yellow-background]*Unknown (MoreInfo)* +
[yellow-background]*includes complete replication flag*
| 24 | 2 | | [yellow-background]*Reserved (wSpare)*
| 26 | 4 | | [yellow-background]*Reserved (dwSpare)*
| 30 | ...  | | [yellow-background]*Server name* +
[yellow-background]*NUL-terminated*
| ... | 2 | "!!" | [yellow-background]*Separator*
| ... | ... | | [yellow-background]*Filename* +
[yellow-background]*NUL-terminated*
|===

==== Replication direction

[cols="1,1,5",options="header"]
|===
| 0 | DIRECTION_NEVER | Never
| 1 | DIRECTION_SEND | Send
| 2 | DIRECTION_RECEIVE | Receive
|===

=== Encryption levels

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0 | DBCREATE_ENCRYPT_NONE | None
| 1 | DBCREATE_ENCRYPT_SIMPLE | Simple
| 2 | DBCREATE_ENCRYPT_MEDIUM | Medium
| 3 | DBCREATE_ENCRYPT_STRONG | Strong
|===

=== User activity records
....
typedef struct { 
        WORD DataReads;                                 /* # of data notes read */ 
        WORD DataAdds;                                  /* # of data notes added */ 
        WORD DataUpdates;                               /* # of data notes updated */ 
        WORD DataDeletes;                               /* # of data notes deleted */ 
        WORD NonDataReads;                              /* # of nondata notes read */ 
        WORD NonDataAdds;                               /* # of nondata notes added */ 
        WORD NonDataUpdates;                    /* # of nondata notes updated */ 
        WORD NonDataDeletes;                    /* # of nondata notes deleted */ 
} ACTIVITY_ENTRY_DETAILS_DUP; 

typedef struct { 
        TIMEDATE First;                         /* Beginning of reporting period */ 
        TIMEDATE Last;                          /* End of reporting period */ 
        DWORD Uses;                                     /* # of uses in reporting period */ 
        DWORD Reads;                            /* # of reads in reporting period */ 
        DWORD Writes;                           /* # of writes in reporting period */ 
        DWORD PrevDayUses;                      /* # of uses in previous 24 hours */ 
        DWORD PrevDayReads;                     /* # of reads in previous 24 hours */ 
        DWORD PrevDayWrites;            /* # of writes in previous 24 hours */ 
        DWORD PrevWeekUses;                     /* # of uses in previous week */ 
        DWORD PrevWeekReads;            /* # of reads in previous week */ 
        DWORD PrevWeekWrites;           /* # of writes in previous week */ 
        DWORD PrevMonthUses;            /* # of uses in previous month */ 
        DWORD PrevMonthReads;           /* # of reads in previous month */ 
        DWORD PrevMonthWrites;          /* # of writes in previous month */ 
} DBACTIVITY; 

typedef struct { 
        TIMEDATE First;                         /* Beginning of reporting period */ 
        TIMEDATE Last;                          /* End of reporting period */ 
        DWORD Uses;                                     /* # of uses in reporting period */ 
        DWORD Reads;                            /* # of reads in reporting period */ 
        DWORD Writes;                           /* # of writes in reporting period */ 
        DWORD Adds; 
        DWORD Updates; 
        DWORD Deletes; 
        DWORD PrevDayUses;                      /* # of uses in previous 24 hours */ 
        DWORD PrevDayReads;                     /* # of reads in previous 24 hours */ 
        DWORD PrevDayAdds; 
        DWORD PrevDayUpdates; 
        DWORD PrevDayDeletes; 
        DWORD PrevWeekUses;                     /* # of uses in previous week */ 
        DWORD PrevWeekReads;            /* # of reads in previous week */ 
        DWORD PrevWeekAdds; 
        DWORD PrevWeekUpdates; 
        DWORD PrevWeekDeletes; 
        DWORD PrevMonthUses;            /* # of uses in previous month */ 
        DWORD PrevMonthReads;           /* # of reads in previous month */ 
        DWORD PrevMonthAdds; 
        DWORD PrevMonthUpdates; 
        DWORD PrevMonthDeletes; 
} DBACTIVITYEXTENDED; 

typedef struct { 
        TIMEDATE Time;                          /* Time of record */ 
        WORD Reads;                                     /* # of data notes read */ 
        WORD Writes;                            /* # of data notes written */ 
        DWORD UserNameOffset;           /* Offset of the user name from the beginning 
                                                                   of this memory block */ 
                                                                /* User names follow -- '\0' terminated */ 
} DBACTIVITY_ENTRY; 

typedef struct { 
        TIMEDATE Time;                          /* Time of record */ 
        ACTIVITY_ENTRY_DETAILS_DUP AEDetails; 
        DWORD UserNameOffset;           /* Offset of the user name from the beginning 
                                                                   of this memory block */ 
                                                                /* User names follow -- '\0' terminated */ 
} DBACTIVITY_ENTRY_EXTENDED; 
....

:numbered!:
[appendix]
== References

`[REFERENCE]`

[cols="1,5",options="header"]
|===
| Title: | 
| Author(s): | 
| Date: | 
| URL: | 
|===

[yellow-background]*TODO: format references as tables.*
....
[IBM]
URL:	http://www.ibm.com

Title:	Lotus C API Notes/Domino 6.0.2 Reference
URL:	http://www-12.lotus.com/ldd/doc/tools/c/6.0.2/api60ref.nsf

Title:	Lotus C API Notes/Domino 6.5 User Guide
URL:	http://www-12.lotus.com/ldd/doc/tools/c/6.5/api65ug.nsf

Title:	Lotus C API Notes/Domino 6.5 Reference
URL:	http://www-12.lotus.com/ldd/doc/tools/c/6.5/api65ref.nsf

Title:	A Database Perspective on Lotus Domino/Notes 
Author(s):	C. Mohan
Date:	June 1999
URL:	http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.58.9616&rep=rep1&type=pdf

Title:	What is Domino / Lotus Notes ?
URL:	http://www.notesdesign.com/ndhtml/ndtutor.htm

Title:	Inside Notes – The architecture of Notes and the Domino Server
Author(s):	Lotus Development Corporation
Date:	2000
URL:	http://www.google.nl/url?sa=t&source=web&ct=res&cd=7&ved=0CCgQFjAG&url=http%3A%2F%2Fwww-12.lotus.com%2Fldd%2Fdoc%2Fuafiles.nsf%2Fdocs%2Finside-notes%2F%24File%2Finsidenotes.pdf&rct=j&q=NSF+RRV+bucket+descriptor&ei=Ru2hS_maIMXi-QbMvtTSBg&usg=AFQjCNGrFa0Pj9unsbyazP0JB79bQp9ZCA
....

[appendix]
== GNU Free Documentation License
Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc. 
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license 
document, but changing it is not allowed.

=== 0. PREAMBLE
The purpose of this License is to make a manual, textbook, or other functional 
and useful document "free" in the sense of freedom: to assure everyone the 
effective freedom to copy and redistribute it, with or without modifying it, 
either commercially or noncommercially. Secondarily, this License preserves for 
the author and publisher a way to get credit for their work, while not being 
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the 
document must themselves be free in the same sense. It complements the GNU 
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software, 
because free software needs free documentation: a free program should come with 
manuals providing the same freedoms that the software does. But this License is 
not limited to software manuals; it can be used for any textual work, 
regardless of subject matter or whether it is published as a printed book. We 
recommend this License principally for works whose purpose is instruction or 
reference.

=== 1. APPLICABILITY AND DEFINITIONS
This License applies to any manual or other work, in any medium, that contains 
a notice placed by the copyright holder saying it can be distributed under the 
terms of this License. Such a notice grants a world-wide, royalty-free license, 
unlimited in duration, to use that work under the conditions stated herein. The 
"Document", below, refers to any such manual or work. Any member of the public 
is a licensee, and is addressed as "you". You accept the license if you copy, 
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or 
a portion of it, either copied verbatim, or with modifications and/or 
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the 
Document that deals exclusively with the relationship of the publishers or 
authors of the Document to the Document's overall subject (or to related 
matters) and contains nothing that could fall directly within that overall 
subject. (Thus, if the Document is in part a textbook of mathematics, a 
Secondary Section may not explain any mathematics.) The relationship could be a 
matter of historical connection with the subject or with related matters, or of 
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are 
designated, as being those of Invariant Sections, in the notice that says that 
the Document is released under this License. If a section does not fit the 
above definition of Secondary then it is not allowed to be designated as 
Invariant. The Document may contain zero Invariant Sections. If the Document 
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as 
Front-Cover Texts or Back-Cover Texts, in the notice that says that the 
Document is released under this License. A Front-Cover Text may be at most 5 
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented 
in a format whose specification is available to the general public, that is 
suitable for revising the document straightforwardly with generic text editors 
or (for images composed of pixels) generic paint programs or (for drawings) 
some widely available drawing editor, and that is suitable for input to text 
formatters or for automatic translation to a variety of formats suitable for 
input to text formatters. A copy made in an otherwise Transparent file format 
whose markup, or absence of markup, has been arranged to thwart or discourage 
subsequent modification by readers is not Transparent. An image format is not 
Transparent if used for any substantial amount of text. A copy that is not 
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without 
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly 
available DTD, and standard-conforming simple HTML, PostScript or PDF designed 
for human modification. Examples of transparent image formats include PNG, XCF 
and JPG. Opaque formats include proprietary formats that can be read and edited 
only by proprietary word processors, SGML or XML for which the DTD and/or 
processing tools are not generally available, and the machine-generated HTML, 
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such 
following pages as are needed to hold, legibly, the material this License 
requires to appear in the title page. For works in formats which do not have 
any title page as such, "Title Page" means the text near the most prominent 
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the 
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title 
either is precisely XYZ or contains XYZ in parentheses following text that 
translates XYZ in another language. (Here XYZ stands for a specific section 
name mentioned below, such as "Acknowledgements", "Dedications", 
"Endorsements", or "History".) To "Preserve the Title" of such a section when 
you modify the Document means that it remains a section "Entitled XYZ" 
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states 
that this License applies to the Document. These Warranty Disclaimers are 
considered to be included by reference in this License, but only as regards 
disclaiming warranties: any other implication that these Warranty Disclaimers 
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING
You may copy and distribute the Document in any medium, either commercially or 
noncommercially, provided that this License, the copyright notices, and the 
license notice saying this License applies to the Document are reproduced in 
all copies, and that you add no other conditions whatsoever to those of this 
License. You may not use technical measures to obstruct or control the reading 
or further copying of the copies you make or distribute. However, you may 
accept compensation in exchange for copies. If you distribute a large enough 
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may 
publicly display copies.

=== 3. COPYING IN QUANTITY
If you publish printed copies (or copies in media that commonly have printed 
covers) of the Document, numbering more than 100, and the Document's license 
notice requires Cover Texts, you must enclose the copies in covers that carry, 
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front 
cover, and Back-Cover Texts on the back cover. Both covers must also clearly 
and legibly identify you as the publisher of these copies. The front cover must 
present the full title with all words of the title equally prominent and 
visible. You may add other material on the covers in addition. Copying with 
changes limited to the covers, as long as they preserve the title of the 
Document and satisfy these conditions, can be treated as verbatim copying in 
other respects.

If the required texts for either cover are too voluminous to fit legibly, you 
should put the first ones listed (as many as fit reasonably) on the actual 
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than 
100, you must either include a machine-readable Transparent copy along with 
each Opaque copy, or state in or with each Opaque copy a computer-network 
location from which the general network-using public has access to download 
using public-standard network protocols a complete Transparent copy of the 
Document, free of added material. If you use the latter option, you must take 
reasonably prudent steps, when you begin distribution of Opaque copies in 
quantity, to ensure that this Transparent copy will remain thus accessible at 
the stated location until at least one year after the last time you distribute 
an Opaque copy (directly or through your agents or retailers) of that edition 
to the public.

It is requested, but not required, that you contact the authors of the Document 
well before redistributing any large number of copies, to give them a chance to 
provide you with an updated version of the Document.

=== 4. MODIFICATIONS
You may copy and distribute a Modified Version of the Document under the 
conditions of sections 2 and 3 above, provided that you release the Modified 
Version under precisely this License, with the Modified Version filling the 
role of the Document, thus licensing distribution and modification of the 
Modified Version to whoever possesses a copy of it. In addition, you must do 
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that 
of the Document, and from those of previous versions (which should, if there 
were any, be listed in the History section of the Document). You may use the 
same title as a previous version if the original publisher of that version 
gives permission. 

B. List on the Title Page, as authors, one or more persons or entities 
responsible for authorship of the modifications in the Modified Version, 
together with at least five of the principal authors of the Document (all of 
its principal authors, if it has fewer than five), unless they release you from 
this requirement. 

C. State on the Title page the name of the publisher of the Modified Version, 
as the publisher. 

D. Preserve all the copyright notices of the Document. 

E. Add an appropriate copyright notice for your modifications adjacent to the 
other copyright notices. 

F. Include, immediately after the copyright notices, a license notice giving 
the public permission to use the Modified Version under the terms of this 
License, in the form shown in the Addendum below. 

G. Preserve in that license notice the full lists of Invariant Sections and 
required Cover Texts given in the Document's license notice. 

H. Include an unaltered copy of this License. 

I. Preserve the section Entitled "History", Preserve its Title, and add to it 
an item stating at least the title, year, new authors, and publisher of the 
Modified Version as given on the Title Page. If there is no section Entitled 
"History" in the Document, create one stating the title, year, authors, and 
publisher of the Document as given on its Title Page, then add an item 
describing the Modified Version as stated in the previous sentence. 

J. Preserve the network location, if any, given in the Document for public 
access to a Transparent copy of the Document, and likewise the network 
locations given in the Document for previous versions it was based on. These 
may be placed in the "History" section. You may omit a network location for a 
work that was published at least four years before the Document itself, or if 
the original publisher of the version it refers to gives permission. 

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the 
Title of the section, and preserve in the section all the substance and tone of 
each of the contributor acknowledgements and/or dedications given therein. 

L. Preserve all the Invariant Sections of the Document, unaltered in their text 
and in their titles. Section numbers or the equivalent are not considered part 
of the section titles. 

M. Delete any section Entitled "Endorsements". Such a section may not be 
included in the Modified Version. 

N. Do not retitle any existing section to be Entitled "Endorsements" or to 
conflict in title with any Invariant Section. 

O. Preserve any Warranty Disclaimers. 

If the Modified Version includes new front-matter sections or appendices that 
qualify as Secondary Sections and contain no material copied from the Document, 
you may at your option designate some or all of these sections as invariant. To 
do this, add their titles to the list of Invariant Sections in the Modified 
Version's license notice. These titles must be distinct from any other section 
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but 
endorsements of your Modified Version by various parties—for example, 
statements of peer review or that the text has been approved by an organization 
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage 
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts 
in the Modified Version. Only one passage of Front-Cover Text and one of 
Back-Cover Text may be added by (or through arrangements made by) any one 
entity. If the Document already includes a cover text for the same cover, 
previously added by you or by arrangement made by the same entity you are 
acting on behalf of, you may not add another; but you may replace the old one, 
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give 
permission to use their names for publicity for or to assert or imply 
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS
You may combine the Document with other documents released under this License, 
under the terms defined in section 4 above for modified versions, provided that 
you include in the combination all of the Invariant Sections of all of the 
original documents, unmodified, and list them all as Invariant Sections of your 
combined work in its license notice, and that you preserve all their Warranty 
Disclaimers.

The combined work need only contain one copy of this License, and multiple 
identical Invariant Sections may be replaced with a single copy. If there are 
multiple Invariant Sections with the same name but different contents, make the 
title of each such section unique by adding at the end of it, in parentheses, 
the name of the original author or publisher of that section if known, or else 
a unique number. Make the same adjustment to the section titles in the list of 
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the 
various original documents, forming one section Entitled "History"; likewise 
combine any sections Entitled "Acknowledgements", and any sections Entitled 
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS
You may make a collection consisting of the Document and other documents 
released under this License, and replace the individual copies of this License 
in the various documents with a single copy that is included in the collection, 
provided that you follow the rules of this License for verbatim copying of each 
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it 
individually under this License, provided you insert a copy of this License 
into the extracted document, and follow this License in all other respects 
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS
A compilation of the Document or its derivatives with other separate and 
independent documents or works, in or on a volume of a storage or distribution 
medium, is called an "aggregate" if the copyright resulting from the 
compilation is not used to limit the legal rights of the compilation's users 
beyond what the individual works permit. When the Document is included in an 
aggregate, this License does not apply to the other works in the aggregate 
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the 
Document, then if the Document is less than one half of the entire aggregate, 
the Document's Cover Texts may be placed on covers that bracket the Document 
within the aggregate, or the electronic equivalent of covers if the Document is 
in electronic form. Otherwise they must appear on printed covers that bracket 
the whole aggregate.

=== 8. TRANSLATION
Translation is considered a kind of modification, so you may distribute 
translations of the Document under the terms of section 4. Replacing Invariant 
Sections with translations requires special permission from their copyright 
holders, but you may include translations of some or all Invariant Sections in 
addition to the original versions of these Invariant Sections. You may include 
a translation of this License, and all the license notices in the Document, and 
any Warranty Disclaimers, provided that you also include the original English 
version of this License and the original versions of those notices and 
disclaimers. In case of a disagreement between the translation and the original 
version of this License or a notice or disclaimer, the original version will 
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or 
"History", the requirement (section 4) to Preserve its Title (section 1) will 
typically require changing the actual title.

=== 9. TERMINATION
You may not copy, modify, sublicense, or distribute the Document except as 
expressly provided under this License. Any attempt otherwise to copy, modify, 
sublicense, or distribute it is void, and will automatically terminate your 
rights under this License.

However, if you cease all violation of this License, then your license from a 
particular copyright holder is reinstated (a) provisionally, unless and until 
the copyright holder explicitly and finally terminates your license, and (b) 
permanently, if the copyright holder fails to notify you of the violation by 
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated 
permanently if the copyright holder notifies you of the violation by some 
reasonable means, this is the first time you have received notice of violation 
of this License (for any work) from that copyright holder, and you cure the 
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses 
of parties who have received copies or rights from you under this License. If 
your rights have been terminated and not permanently reinstated, receipt of a 
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE
The Free Software Foundation may publish new, revised versions of the GNU Free 
Documentation License from time to time. Such new versions will be similar in 
spirit to the present version, but may differ in detail to address new problems 
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the 
Document specifies that a particular numbered version of this License "or any 
later version" applies to it, you have the option of following the terms and 
conditions either of that specified version or of any later version that has 
been published (not as a draft) by the Free Software Foundation. If the 
Document does not specify a version number of this License, you may choose any 
version ever published (not as a draft) by the Free Software Foundation. If the 
Document specifies that a proxy can decide which future versions of this 
License can be used, that proxy's public statement of acceptance of a version 
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING
"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide 
Web server that publishes copyrightable works and also provides prominent 
facilities for anybody to edit those works. A public wiki that anybody can edit 
is an example of such a server. A "Massive Multiauthor Collaboration" (or 
"MMC") contained in the site means any set of copyrightable works thus 
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license 
published by Creative Commons Corporation, a not-for-profit corporation with a 
principal place of business in San Francisco, California, as well as future 
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as 
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and 
if all works that were first published under this License somewhere other than 
this MMC, and subsequently incorporated in whole or in part into the MMC, (1) 
had no cover texts or invariant sections, and (2) were thus incorporated prior 
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under 
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC 
is eligible for relicensing.

